/*
 * This file is generated by jOOQ.
 */
package com.starterproject.config.jooq.tables.records;


import com.starterproject.config.jooq.tables.Users;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersRecord extends UpdatableRecordImpl<UsersRecord> implements Record6<Integer, String, String, String, Byte, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>ed_mex.users.idUser</code>.
     */
    public void setIduser(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>ed_mex.users.idUser</code>.
     */
    public Integer getIduser() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>ed_mex.users.username</code>.
     */
    public void setUsername(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>ed_mex.users.username</code>.
     */
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>ed_mex.users.password</code>.
     */
    public void setPassword(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>ed_mex.users.password</code>.
     */
    public String getPassword() {
        return (String) get(2);
    }

    /**
     * Setter for <code>ed_mex.users.role</code>.
     */
    public void setRole(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>ed_mex.users.role</code>.
     */
    public String getRole() {
        return (String) get(3);
    }

    /**
     * Setter for <code>ed_mex.users.enabled</code>.
     */
    public void setEnabled(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>ed_mex.users.enabled</code>.
     */
    public Byte getEnabled() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>ed_mex.users.idRoom</code>.
     */
    public void setIdroom(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>ed_mex.users.idRoom</code>.
     */
    public Integer getIdroom() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, String, String, Byte, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, String, String, String, Byte, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Users.USERS.IDUSER;
    }

    @Override
    public Field<String> field2() {
        return Users.USERS.USERNAME;
    }

    @Override
    public Field<String> field3() {
        return Users.USERS.PASSWORD;
    }

    @Override
    public Field<String> field4() {
        return Users.USERS.ROLE;
    }

    @Override
    public Field<Byte> field5() {
        return Users.USERS.ENABLED;
    }

    @Override
    public Field<Integer> field6() {
        return Users.USERS.IDROOM;
    }

    @Override
    public Integer component1() {
        return getIduser();
    }

    @Override
    public String component2() {
        return getUsername();
    }

    @Override
    public String component3() {
        return getPassword();
    }

    @Override
    public String component4() {
        return getRole();
    }

    @Override
    public Byte component5() {
        return getEnabled();
    }

    @Override
    public Integer component6() {
        return getIdroom();
    }

    @Override
    public Integer value1() {
        return getIduser();
    }

    @Override
    public String value2() {
        return getUsername();
    }

    @Override
    public String value3() {
        return getPassword();
    }

    @Override
    public String value4() {
        return getRole();
    }

    @Override
    public Byte value5() {
        return getEnabled();
    }

    @Override
    public Integer value6() {
        return getIdroom();
    }

    @Override
    public UsersRecord value1(Integer value) {
        setIduser(value);
        return this;
    }

    @Override
    public UsersRecord value2(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public UsersRecord value3(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public UsersRecord value4(String value) {
        setRole(value);
        return this;
    }

    @Override
    public UsersRecord value5(Byte value) {
        setEnabled(value);
        return this;
    }

    @Override
    public UsersRecord value6(Integer value) {
        setIdroom(value);
        return this;
    }

    @Override
    public UsersRecord values(Integer value1, String value2, String value3, String value4, Byte value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersRecord
     */
    public UsersRecord() {
        super(Users.USERS);
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(Integer iduser, String username, String password, String role, Byte enabled, Integer idroom) {
        super(Users.USERS);

        setIduser(iduser);
        setUsername(username);
        setPassword(password);
        setRole(role);
        setEnabled(enabled);
        setIdroom(idroom);
        resetChangedOnNotNull();
    }
}
