/*
 * This file is generated by jOOQ.
 */
package com.starterproject.config.jooq;


import com.starterproject.config.jooq.tables.Message;
import com.starterproject.config.jooq.tables.MessageBck;
import com.starterproject.config.jooq.tables.Room;
import com.starterproject.config.jooq.tables.Users;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EdMex extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>ed_mex</code>
     */
    public static final EdMex ED_MEX = new EdMex();

    /**
     * The table <code>ed_mex.message</code>.
     */
    public final Message MESSAGE = Message.MESSAGE;

    /**
     * The table <code>ed_mex.message_bck</code>.
     */
    public final MessageBck MESSAGE_BCK = MessageBck.MESSAGE_BCK;

    /**
     * The table <code>ed_mex.room</code>.
     */
    public final Room ROOM = Room.ROOM;

    /**
     * The table <code>ed_mex.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private EdMex() {
        super("ed_mex", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Message.MESSAGE,
            MessageBck.MESSAGE_BCK,
            Room.ROOM,
            Users.USERS
        );
    }
}
