/*
 * This file is generated by jOOQ.
 */
package com.starterproject.config.jooq;


import com.starterproject.config.jooq.tables.Users;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in ed_mex.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index USERS_FK_IDROOM_IDX = Internal.createIndex(DSL.name("fk_idroom_idx"), Users.USERS, new OrderField[] { Users.USERS.IDROOM }, false);
}
