/*
 * This file is generated by jOOQ.
 */
package com.starterproject.config.jooq;


import com.starterproject.config.jooq.tables.Message;
import com.starterproject.config.jooq.tables.MessageBck;
import com.starterproject.config.jooq.tables.Room;
import com.starterproject.config.jooq.tables.Users;


/**
 * Convenience access to all tables in ed_mex.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>ed_mex.message</code>.
     */
    public static final Message MESSAGE = Message.MESSAGE;

    /**
     * The table <code>ed_mex.message_bck</code>.
     */
    public static final MessageBck MESSAGE_BCK = MessageBck.MESSAGE_BCK;

    /**
     * The table <code>ed_mex.room</code>.
     */
    public static final Room ROOM = Room.ROOM;

    /**
     * The table <code>ed_mex.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
